    name: Deploy

    on:
      push:
        branches: [main]
        
    jobs:
        ci:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v3

            - name: Cypress run
              uses: cypress-io/github-action@v6

            - name: Deploy to render
              if: github.ref == 'refs/heads/main'
              env:
                DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
              run: |
                curl "$DEPLOY_URL"