# Name of workflow
name: Lint and Test workflow
#nothing
# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - develop

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js 21.x
        uses: actions/setup-node@v1
        with:
          node-version: 21.x

      # Install dependencies
      - name: 🧰 Install Deps
        run: npm install
        
      # Run lint
      - name: Run Lint
        run: npm run lint

      # Run build
      - name: Run Build
        run: npm run build

      # Start the application
      - name: Start the Application
        run: npm run start &

      # Wait for the server to be ready
      - name: Wait for Server
        run: npx wait-on http://localhost:3001

      # Run Cypress tests
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run start
          wait-on: http://localhost:3001
        